language: node_js
node_js:
#  - "0.8"
  - "0.10"
  - "0.12"

before_install:
  - "if [[ `node -v` == v0.8.* ]]; then npm install -g npm || exit 0; fi"

script:
  - "mocha -- test test/json test/model test/protocol test/query test/services test/signers test/xml test/s3"

env:
  matrix:
    - COVERAGE=1

sudo: false

# env:
#   global:
#     - secure: "..."
#   matrix:
#     - UNIT=1
#     - AWS_REGION=us-east-1 INTEGRATION=1
