environment:
  matrix:
    nodejs_version: "4"
    nodejs_version: "5"
    nodejs_version: "6"
    nodejs_version: "7"
    nodejs_version: "8"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run unit

build: off
